### ISSUE TITLE
生成jar文件正常但是导入插件报错  求解

### ISSUE THREAD

**Issue by ldbfpiaoran** [src-kun/transparent-cap#1]
自己写的东西也是这个问题 看到了这个 然后同样错误。。。
java.lang.NoClassDefFoundError: redis/clients/jedis/Jedis
	at burp.BurpExtender.<init>(BurpExtender.java:15)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at burp.sue.a(Unknown Source)
	at burp.sue.<init>(Unknown Source)
	at burp.mn.a(Unknown Source)
	at burp.ooh.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.Jedis
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

导入之后会有这样的异常·....  

jedis环境变量添加了啊

**Comment by src-kun** [comment]
你用解压软件解压jar包，看看有redis这个文件夹吗
![image](https://user-images.githubusercontent.com/16421223/39558623-cd1ae578-4ec2-11e8-90dc-d15411d3ae04.png)

**Comment by ldbfpiaoran** [comment]
有的呀  而且在eclipse生成也没有报错==

**Comment by ldbfpiaoran** [comment]
=-=  你是说burp插件那个么 那里不会有redis这个文件夹吧==

**Comment by src-kun** [comment]
会有的，因为你导入jar包了，解压你导出的扩展jar包
